import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
];

// Basic translations for common UI elements
const translations: Record<string, Record<string, string>> = {
  en: {
    home: 'Home',
    shop: 'Shop',
    sales: 'Sales',
    aboutUs: 'About Us',
    contact: 'Contact',
    myBag: 'My Bag',
    login: 'Login',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    myAccount: 'My Account',
    myOrders: 'My Orders',
    myWishlist: 'My Wishlist',
    settings: 'Settings',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    addToBag: 'Add to Bag',
    buyNow: 'Buy Now',
    checkout: 'Checkout',
    continueShopping: 'Continue Shopping',
    yourBagIsEmpty: 'Your bag is empty',
    subtotal: 'Subtotal',
    total: 'Total',
    deliveryFee: 'Delivery Fee',
    search: 'Search',
    categories: 'Categories',
    products: 'Products',
    filters: 'Filters',
    sortBy: 'Sort By',
    price: 'Price',
    size: 'Size',
    quantity: 'Quantity',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    welcomeBack: 'Welcome back!',
    followUs: 'Follow us',
    orderHistory: 'Order History',
    addresses: 'Addresses',
    notifications: 'Notifications',
    security: 'Security',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
  },
  bn: {
    home: 'হোম',
    shop: 'দোকান',
    sales: 'বিক্রয়',
    aboutUs: 'আমাদের সম্পর্কে',
    contact: 'যোগাযোগ',
    myBag: 'আমার ব্যাগ',
    login: 'লগইন',
    signUp: 'সাইন আপ',
    signOut: 'সাইন আউট',
    myAccount: 'আমার অ্যাকাউন্ট',
    myOrders: 'আমার অর্ডার',
    myWishlist: 'আমার পছন্দের তালিকা',
    settings: 'সেটিংস',
    language: 'ভাষা',
    currency: 'মুদ্রা',
    theme: 'থিম',
    light: 'লাইট',
    dark: 'ডার্ক',
    system: 'সিস্টেম',
    addToBag: 'ব্যাগে যোগ করুন',
    buyNow: 'এখনই কিনুন',
    checkout: 'চেকআউট',
    continueShopping: 'কেনাকাটা চালিয়ে যান',
    yourBagIsEmpty: 'আপনার ব্যাগ খালি',
    subtotal: 'সাবটোটাল',
    total: 'মোট',
    deliveryFee: 'ডেলিভারি ফি',
    search: 'অনুসন্ধান',
    categories: 'বিভাগ',
    products: 'পণ্য',
    filters: 'ফিল্টার',
    sortBy: 'সাজানো',
    price: 'মূল্য',
    size: 'সাইজ',
    quantity: 'পরিমাণ',
    inStock: 'স্টকে আছে',
    outOfStock: 'স্টক নেই',
    welcomeBack: 'স্বাগতম!',
    followUs: 'আমাদের অনুসরণ করুন',
    orderHistory: 'অর্ডার ইতিহাস',
    addresses: 'ঠিকানা',
    notifications: 'বিজ্ঞপ্তি',
    security: 'নিরাপত্তা',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    loading: 'লোড হচ্ছে...',
  },
  hi: {
    home: 'होम',
    shop: 'दुकान',
    sales: 'बिक्री',
    aboutUs: 'हमारे बारे में',
    contact: 'संपर्क',
    myBag: 'मेरा बैग',
    login: 'लॉग इन',
    signUp: 'साइन अप',
    signOut: 'साइन आउट',
    myAccount: 'मेरा खाता',
    myOrders: 'मेरे ऑर्डर',
    myWishlist: 'मेरी विशलिस्ट',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    currency: 'मुद्रा',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    system: 'सिस्टम',
    addToBag: 'बैग में डालें',
    buyNow: 'अभी खरीदें',
    checkout: 'चेकआउट',
    continueShopping: 'खरीदारी जारी रखें',
    yourBagIsEmpty: 'आपका बैग खाली है',
    subtotal: 'उपकुल',
    total: 'कुल',
    deliveryFee: 'डिलीवरी शुल्क',
    search: 'खोजें',
    categories: 'श्रेणियां',
    products: 'उत्पाद',
    filters: 'फ़िल्टर',
    sortBy: 'क्रमबद्ध करें',
    price: 'कीमत',
    size: 'साइज़',
    quantity: 'मात्रा',
    inStock: 'स्टॉक में',
    outOfStock: 'स्टॉक में नहीं',
    welcomeBack: 'वापसी पर स्वागत!',
    followUs: 'हमें फॉलो करें',
    orderHistory: 'ऑर्डर इतिहास',
    addresses: 'पते',
    notifications: 'सूचनाएं',
    security: 'सुरक्षा',
    save: 'सेव',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    loading: 'लोड हो रहा है...',
  },
  ar: {
    home: 'الرئيسية',
    shop: 'تسوق',
    sales: 'تخفيضات',
    aboutUs: 'من نحن',
    contact: 'اتصل بنا',
    myBag: 'حقيبتي',
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    myAccount: 'حسابي',
    myOrders: 'طلباتي',
    myWishlist: 'قائمة أمنياتي',
    settings: 'الإعدادات',
    language: 'اللغة',
    currency: 'العملة',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    system: 'النظام',
    addToBag: 'أضف للحقيبة',
    buyNow: 'اشتر الآن',
    checkout: 'الدفع',
    continueShopping: 'متابعة التسوق',
    yourBagIsEmpty: 'حقيبتك فارغة',
    subtotal: 'المجموع الفرعي',
    total: 'المجموع',
    deliveryFee: 'رسوم التوصيل',
    search: 'بحث',
    categories: 'الفئات',
    products: 'المنتجات',
    filters: 'الفلاتر',
    sortBy: 'ترتيب حسب',
    price: 'السعر',
    size: 'الحجم',
    quantity: 'الكمية',
    inStock: 'متوفر',
    outOfStock: 'غير متوفر',
    welcomeBack: 'أهلاً بعودتك!',
    followUs: 'تابعنا',
    orderHistory: 'سجل الطلبات',
    addresses: 'العناوين',
    notifications: 'الإشعارات',
    security: 'الأمان',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    loading: 'جارٍ التحميل...',
  },
  id: {
    home: 'Beranda',
    shop: 'Toko',
    sales: 'Diskon',
    aboutUs: 'Tentang Kami',
    contact: 'Kontak',
    myBag: 'Tas Saya',
    login: 'Masuk',
    signUp: 'Daftar',
    signOut: 'Keluar',
    myAccount: 'Akun Saya',
    myOrders: 'Pesanan Saya',
    myWishlist: 'Wishlist Saya',
    settings: 'Pengaturan',
    language: 'Bahasa',
    currency: 'Mata Uang',
    theme: 'Tema',
    light: 'Terang',
    dark: 'Gelap',
    system: 'Sistem',
    addToBag: 'Tambah ke Tas',
    buyNow: 'Beli Sekarang',
    checkout: 'Checkout',
    continueShopping: 'Lanjut Belanja',
    yourBagIsEmpty: 'Tas Anda kosong',
    subtotal: 'Subtotal',
    total: 'Total',
    deliveryFee: 'Biaya Pengiriman',
    search: 'Cari',
    categories: 'Kategori',
    products: 'Produk',
    filters: 'Filter',
    sortBy: 'Urutkan',
    price: 'Harga',
    size: 'Ukuran',
    quantity: 'Jumlah',
    inStock: 'Tersedia',
    outOfStock: 'Habis',
    welcomeBack: 'Selamat datang kembali!',
    followUs: 'Ikuti kami',
    orderHistory: 'Riwayat Pesanan',
    addresses: 'Alamat',
    notifications: 'Notifikasi',
    security: 'Keamanan',
    save: 'Simpan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Edit',
    loading: 'Memuat...',
  },
  th: {
    home: 'หน้าแรก',
    shop: 'ร้านค้า',
    sales: 'ลดราคา',
    aboutUs: 'เกี่ยวกับเรา',
    contact: 'ติดต่อ',
    myBag: 'กระเป๋าของฉัน',
    login: 'เข้าสู่ระบบ',
    signUp: 'สมัครสมาชิก',
    signOut: 'ออกจากระบบ',
    myAccount: 'บัญชีของฉัน',
    myOrders: 'คำสั่งซื้อของฉัน',
    myWishlist: 'รายการโปรด',
    settings: 'ตั้งค่า',
    language: 'ภาษา',
    currency: 'สกุลเงิน',
    theme: 'ธีม',
    light: 'สว่าง',
    dark: 'มืด',
    system: 'ระบบ',
    addToBag: 'เพิ่มลงกระเป๋า',
    buyNow: 'ซื้อเลย',
    checkout: 'ชำระเงิน',
    continueShopping: 'ช้อปต่อ',
    yourBagIsEmpty: 'กระเป๋าของคุณว่างเปล่า',
    subtotal: 'ยอดรวม',
    total: 'รวมทั้งหมด',
    deliveryFee: 'ค่าจัดส่ง',
    search: 'ค้นหา',
    categories: 'หมวดหมู่',
    products: 'สินค้า',
    filters: 'ตัวกรอง',
    sortBy: 'เรียงตาม',
    price: 'ราคา',
    size: 'ขนาด',
    quantity: 'จำนวน',
    inStock: 'มีสินค้า',
    outOfStock: 'สินค้าหมด',
    welcomeBack: 'ยินดีต้อนรับกลับ!',
    followUs: 'ติดตามเรา',
    orderHistory: 'ประวัติคำสั่งซื้อ',
    addresses: 'ที่อยู่',
    notifications: 'การแจ้งเตือน',
    security: 'ความปลอดภัย',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    delete: 'ลบ',
    edit: 'แก้ไข',
    loading: 'กำลังโหลด...',
  },
  vi: {
    home: 'Trang chủ',
    shop: 'Cửa hàng',
    sales: 'Giảm giá',
    aboutUs: 'Về chúng tôi',
    contact: 'Liên hệ',
    myBag: 'Giỏ hàng',
    login: 'Đăng nhập',
    signUp: 'Đăng ký',
    signOut: 'Đăng xuất',
    myAccount: 'Tài khoản',
    myOrders: 'Đơn hàng',
    myWishlist: 'Yêu thích',
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    currency: 'Tiền tệ',
    theme: 'Giao diện',
    light: 'Sáng',
    dark: 'Tối',
    system: 'Hệ thống',
    addToBag: 'Thêm vào giỏ',
    buyNow: 'Mua ngay',
    checkout: 'Thanh toán',
    continueShopping: 'Tiếp tục mua sắm',
    yourBagIsEmpty: 'Giỏ hàng trống',
    subtotal: 'Tạm tính',
    total: 'Tổng',
    deliveryFee: 'Phí vận chuyển',
    search: 'Tìm kiếm',
    categories: 'Danh mục',
    products: 'Sản phẩm',
    filters: 'Bộ lọc',
    sortBy: 'Sắp xếp',
    price: 'Giá',
    size: 'Kích thước',
    quantity: 'Số lượng',
    inStock: 'Còn hàng',
    outOfStock: 'Hết hàng',
    welcomeBack: 'Chào mừng trở lại!',
    followUs: 'Theo dõi chúng tôi',
    orderHistory: 'Lịch sử đơn hàng',
    addresses: 'Địa chỉ',
    notifications: 'Thông báo',
    security: 'Bảo mật',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    edit: 'Sửa',
    loading: 'Đang tải...',
  },
};

interface LanguageStore {
  selectedLanguage: Language;
  languages: Language[];
  setLanguage: (code: string) => void;
  t: (key: string) => string;
}

export const useLanguage = create<LanguageStore>()(
  persist(
    (set, get) => ({
      selectedLanguage: languages[0],
      languages,

      setLanguage: (code: string) => {
        const language = languages.find(l => l.code === code);
        if (language) {
          set({ selectedLanguage: language });
        }
      },

      t: (key: string) => {
        const { selectedLanguage } = get();
        const langTranslations = translations[selectedLanguage.code] || translations.en;
        return langTranslations[key] || translations.en[key] || key;
      },
    }),
    {
      name: 'almans-language',
    }
  )
);
